import "@/app/_styles/output.css";
import AuthProviders from "./_components/AuthProviders";
import QueryProviders from "./_components/QueryProviders";

export const metadata = {
  title: "BeatBot Studio",
  description: "Generated by create next app",
  icons: {
    icon: "/BeatBot.png",
  },
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AuthProviders>
          <QueryProviders>{children}</QueryProviders>
        </AuthProviders>
      </body>
    </html>
  );
}
